<h1>Editar Usuario</h1>

<?php

$nome = $form->get('nome');
$nome->setAttribute('class', 'form-control');

$email = $form->get('email');
$email->setAttribute('class', 'form-control');

$senha = $form->get('senha');
$senha->setAttribute('class', 'form-control');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('user', ['action'=>'edit', 'id'=>$id]));
$form->prepare();

echo $this->form()->openTag($form);

?>

<div class="form-group">
    <?=$this->formLabel($nome); ?>
    <?=$this->formElement($nome); ?>
</div>

<div class="form-group">
    <?=$this->formLabel($email); ?>
    <?=$this->formElement($email); ?>
</div>

<div class="form-group">
    <?=$this->formLabel($senha); ?>
    <?=$this->formElement($senha); ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
?>
