<?php $this->headTitle("Users"); ?>

<h1>Users</h1>

<p>
    <a class="btn btn-success" href="<?=$this->url('user', ['action'=>'add']); ?>">
        <span class="glyphicon glyphicon-user">&nbsp;Cadastrar</a>
</p>

<table class="table">
    <tr>
        <th>Nome</th>
        <th>E-mail</th>
        <th>Senha</th>
        <th>Action</th>
    </tr>
    <?php foreach ($users as $user): ?>
        <tr>
            <td><?=$this->escapeHtml($user->nome); ?></td>
            <td><?=$this->escapeHtml($user->email); ?></td>
            <td><?=$this->escapeHtml($user->senha); ?></td>
            <td>
                <a class="btn btn-info" href="<?=$this->url('user', ['action'=>'edit', 'id'=>$user->id]); ?>">
                    <span class="glyphicon glyphicon-pencil"></span>&nbsp;Editar</a>
                <a class="btn btn-danger" href="<?=$this->url('user', ['action'=>'delete', 'id'=>$user->id]); ?>">
                    <span class="glyphicon glyphicon-trash">&nbsp;Excluir</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>